{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pw-check-{{ template "basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.ingress.annotations }}
  annotations: {{ .Values.ingress.annotations | toYaml | nindent 4 }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: pw-check-{{ template "basename" . }}
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClass }}
  ingressClassName: {{ .Values.ingress.ingressClass }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - backend:
              service:
                name:  {{ .Values.deployment.pwCheck.prosodyService }}
                port:
                  number: 5280
            path: /all-rooms
            pathType: Exact
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
{{- end }}