package-chart:
  image: alpine/k8s:1.25.15
  before_script:
    - helm registry login "${CI_REGISTRY}" -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}"
  script:
    - export CHART_VERSION=$(echo "${CI_COMMIT_TAG:-chart-0.0.0+${CI_COMMIT_SHORT_SHA}}" | cut -b 7-)
    - yq e -i '.version = (strenv(CHART_VERSION))' ./chart/Chart.yaml
    - helm package -d build/ -u ./chart
    - helm push build/*-${CHART_VERSION}.tgz "oci://${CI_REGISTRY_IMAGE}/chart"
  rules:
    - if: $CI_COMMIT_TAG =~ /^chart-.*/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
