apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pw-check-{{ template "basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: conference-mapper
data:
  auth: {{ .Values.deployment.pwCheck.auth }}