apiVersion: v1
kind: Service
metadata:
  name: conference-mapper-{{ include "basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector: {{- include "matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: conference-mapper